# Get all books
GET http://citweb.lanecc.net:5007/books HTTP/1.1
Content-Type: application/json

###

# Create a book
POST http://citweb.lanecc.net:5007/books HTTP/1.1
Content-Type: application/json

{
  "title": "Harry Potter"
}

###

# Update a book
PUT http://citweb.lanecc.net:5007/books/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Dark Tower"
}

###

# Delete a book
DELETE http://citweb.lanecc.net:5007/books/1 HTTP/1.1
Content-Type: application/json